
let words = [ 
    { "word": "apple", "meaning": "আপেল", "pronunciation": "অ্যাপল" },
    { "word": "ball", "meaning": "বল", "pronunciation": "বল" },
    { "word": "cat", "meaning": "বিড়াল", "pronunciation": "ক্যাট" },
    { "word": "dog", "meaning": "কুকুর", "pronunciation": "ডগ" },
    { "word": "elephant", "meaning": "হাতি", "pronunciation": "এলিফ্যান্ট" },
    { "word": "fish", "meaning": "মাছ", "pronunciation": "ফিশ" },
    { "word": "goat", "meaning": "ছাগল", "pronunciation": "গোট" },
    { "word": "hat", "meaning": "টুপি", "pronunciation": "হ্যাট" },
    { "word": "ice", "meaning": "বরফ", "pronunciation": "আইস" },
    { "word": "jug", "meaning": "জগ", "pronunciation": "জগ" },
    { "word": "kite", "meaning": "ঘুড়ি", "pronunciation": "কাইট" },
    { "word": "lion", "meaning": "সিংহ", "pronunciation": "লায়ন" },
    { "word": "monkey", "meaning": "বানর", "pronunciation": "মাঙ্কি" },
    { "word": "nest", "meaning": "বাসা", "pronunciation": "নেস্ট" },
    { "word": "orange", "meaning": "কমলা", "pronunciation": "অরেঞ্জ" },
    { "word": "parrot", "meaning": "তোতাপাখি", "pronunciation": "প্যারট" },
    { "word": "queen", "meaning": "রাণী", "pronunciation": "কুইন" },
    { "word": "rat", "meaning": "ইঁদুর", "pronunciation": "র্যাট" },
    { "word": "sun", "meaning": "সূর্য", "pronunciation": "সান" },
    { "word": "tiger", "meaning": "বাঘ", "pronunciation": "টাইগার" },
    { "word": "umbrella", "meaning": "ছাতা", "pronunciation": "আমব্রেলা" },
    { "word": "vase", "meaning": "ফুলদানি", "pronunciation": "ভাস" },
    { "word": "watch", "meaning": "ঘড়ি", "pronunciation": "ওয়াচ" },
    { "word": "xylophone", "meaning": "জাইলোফোন", "pronunciation": "জাইলোফোন" },
    { "word": "yak", "meaning": "যাক", "pronunciation": "ইয়াক" },
    { "word": "zebra", "meaning": "জেব্রা", "pronunciation": "জেব্রা" },
    { "word": "I", "meaning": "আমি", "pronunciation": "আই" },
    { "word": "you", "meaning": "তুমি", "pronunciation": "ইউ" },
    { "word": "he", "meaning": "সে (ছেলে)", "pronunciation": "হি" },
    { "word": "she", "meaning": "সে (মেয়ে)", "pronunciation": "শি" },
    { "word": "it", "meaning": "এটি", "pronunciation": "ইট" },
    { "word": "we", "meaning": "আমরা", "pronunciation": "উই" },
    { "word": "they", "meaning": "তারা", "pronunciation": "দে" },
    { "word": "me", "meaning": "আমাকে", "pronunciation": "মি" },
    { "word": "him", "meaning": "তাকে (ছেলে)", "pronunciation": "হিম" },
    { "word": "her", "meaning": "তাকে (মেয়ে)", "pronunciation": "হার" },
    { "word": "us", "meaning": "আমাদের", "pronunciation": "আস" },
    { "word": "them", "meaning": "তাদের", "pronunciation": "দেম" },
    { "word": "happiness", "meaning": "সুখ", "pronunciation": "হ্যাপিনেস" },
    { "word": "love", "meaning": "ভালবাসা", "pronunciation": "লাভ" },
    { "word": "anger", "meaning": "রাগ", "pronunciation": "অ্যাংগার" },
    { "word": "freedom", "meaning": "স্বাধীনতা", "pronunciation": "ফ্রিডম" },
    { "word": "justice", "meaning": "ন্যায়বিচার", "pronunciation": "জাস্টিস" },
    { "word": "beauty", "meaning": "সৌন্দর্য", "pronunciation": "বিউটি" },
    { "word": "fear", "meaning": "ভয়", "pronunciation": "ফিয়ার" },
    { "word": "courage", "meaning": "সাহস", "pronunciation": "কারেজ" },
    { "word": "honesty", "meaning": "সততা", "pronunciation": "অনেস্টি" },
    { "word": "friendship", "meaning": "বন্ধুত্ব", "pronunciation": "ফ্রেন্ডশিপ" },
    { "word": "faith", "meaning": "বিশ্বাস", "pronunciation": "ফেইথ" },
    { "word": "knowledge", "meaning": "জ্ঞান", "pronunciation": "নলেজ" },
    { "word": "pain", "meaning": "ব্যথা", "pronunciation": "পেইন" },
    { "word": "truth", "meaning": "সত্য", "pronunciation": "ট্রুথ" },
    { "word": "kindness", "meaning": "দয়া", "pronunciation": "কাইন্ডনেস" },
    { "word": "patience", "meaning": "ধৈর্য", "pronunciation": "পেশেন্স" },
    { "word": "run", "meaning": "দৌড়ানো", "pronunciation": "রান" },
    { "word": "eat", "meaning": "খাওয়া", "pronunciation": "ইট" },
    { "word": "sleep", "meaning": "ঘুমানো", "pronunciation": "স্লিপ" },
    { "word": "speak", "meaning": "কথা বলা", "pronunciation": "স্পিক" },
    { "word": "write", "meaning": "লেখা", "pronunciation": "রাইট" },
    { "word": "read", "meaning": "পড়া", "pronunciation": "রিড" },
    { "word": "sing", "meaning": "গাওয়া", "pronunciation": "সিং" },
    { "word": "drink", "meaning": "পান করা", "pronunciation": "ড্রিংক" },
    { "word": "dance", "meaning": "নাচা", "pronunciation": "ডান্স" },
    { "word": "listen", "meaning": "শোনা", "pronunciation": "লিসেন" },
    { "word": "think", "meaning": "ভাবা", "pronunciation": "থিঙ্ক" },
    { "word": "see", "meaning": "দেখা", "pronunciation": "সি" },
    { "word": "buy", "meaning": "কেনা", "pronunciation": "বাই" },
    { "word": "teach", "meaning": "শিক্ষা দেওয়া", "pronunciation": "টিচ" },
    { "word": "learn", "meaning": "শেখা", "pronunciation": "লার্ন" },
    { "word": "give", "meaning": "দেওয়া", "pronunciation": "গিভ" },
    { "word": "take", "meaning": "নেওয়া", "pronunciation": "টেক" },
    { "word": "call", "meaning": "ডাকা", "pronunciation": "কল" },
    { "word": "run", "meaning": "দৌড়ানো", "pronunciation": "রান" },
    { "word": "quickly", "meaning": "দ্রুত", "pronunciation": "কুইকলি" },
    { "word": "slowly", "meaning": "ধীরে", "pronunciation": "স্লোলি" },
    { "word": "silently", "meaning": "নিঃশব্দে", "pronunciation": "সাইলেন্টলি" },
    { "word": "happily", "meaning": "খুশিতে", "pronunciation": "হ্যাপিলি" },
    { "word": "angrily", "meaning": "রাগের সাথে", "pronunciation": "অ্যাংগ্রিলি" },
    { "word": "easily", "meaning": "সহজে", "pronunciation": "ইজিলি" },
    { "word": "sadly", "meaning": "দুঃখের সাথে", "pronunciation": "স্যাডলি" },
    { "word": "quietly", "meaning": "শান্তভাবে", "pronunciation": "কুয়ায়েটলি" },
    { "word": "loudly", "meaning": "জোরে", "pronunciation": "লাউডলি" },
    { "word": "badly", "meaning": "খারাপভাবে", "pronunciation": "ব্যাডলি" },
    { "word": "carefully", "meaning": "সাবধানে", "pronunciation": "কেয়ারফুলি" },
    { "word": "beautifully", "meaning": "সুন্দরভাবে", "pronunciation": "বিউটিফুলি" },
    { "word": "calmly", "meaning": "শান্তভাবে", "pronunciation": "কাল্মলি" },
    { "word": "truly", "meaning": "সত্যিই", "pronunciation": "ট্রুলি" },
    { "word": "honestly", "meaning": "সততার সাথে", "pronunciation": "অনেস্টলি" },
    { "word": "beautiful", "meaning": "সুন্দর", "pronunciation": "বিউটিফুল" },
    { "word": "happy", "meaning": "খুশি", "pronunciation": "হ্যাপি" },
    { "word": "sad", "meaning": "দুঃখী", "pronunciation": "স্যাড" },
    { "word": "angry", "meaning": "রাগান্বিত", "pronunciation": "অ্যাংরি" },
    { "word": "brave", "meaning": "সাহসী", "pronunciation": "ব্রেভ" },
    { "word": "smart", "meaning": "স্মার্ট", "pronunciation": "স্মার্ট" },
    { "word": "lazy", "meaning": "অলস", "pronunciation": "লেজি" },
    { "word": "strong", "meaning": "শক্তিশালী", "pronunciation": "স্ট্রং" },
    { "word": "weak", "meaning": "দুর্বল", "pronunciation": "উইক" },
    { "word": "big", "meaning": "বড়", "pronunciation": "বিগ" },
    { "word": "small", "meaning": "ছোট", "pronunciation": "স্মল" },
    { "word": "fast", "meaning": "দ্রুত", "pronunciation": "ফাস্ট" },
    { "word": "slow", "meaning": "ধীর", "pronunciation": "স্লো" },
    { "word": "young", "meaning": "যুবা", "pronunciation": "ইয়াং" },
    { "word": "old", "meaning": "বৃদ্ধ", "pronunciation": "ওল্ড" },
    { "word": "in", "meaning": "ভিতরে", "pronunciation": "ইন" },
    { "word": "on", "meaning": "উপর", "pronunciation": "অন" },
    { "word": "under", "meaning": "নিচে", "pronunciation": "আন্ডার" },
    { "word": "over", "meaning": "উপর দিয়ে", "pronunciation": "ওভার" },
    { "word": "between", "meaning": "মধ্যে", "pronunciation": "বিটুইন" },
    { "word": "behind", "meaning": "পিছনে", "pronunciation": "বিহাইন্ড" },
    { "word": "in front of", "meaning": "সামনে", "pronunciation": "ইন ফ্রন্ট অফ" },
    { "word": "next to", "meaning": "পাশে", "pronunciation": "নেক্সট টু" },
    { "word": "beside", "meaning": "পাশে", "pronunciation": "বিসাইড" },
    { "word": "above", "meaning": "উপরে", "pronunciation": "অ্যাবাভ" },
    { "word": "below", "meaning": "নিচে", "pronunciation": "বিলো" },
    { "word": "around", "meaning": "চারপাশে", "pronunciation": "অ্যারাউন্ড" },
    { "word": "through", "meaning": "মাধ্যমে", "pronunciation": "থ্রু" },
    { "word": "towards", "meaning": "দিকে", "pronunciation": "টুওয়ার্ডস" },
    { "word": "with", "meaning": "সঙ্গে", "pronunciation": "উইথ" },
    { "word": "and", "meaning": "এবং", "pronunciation": "অ্যান্ড" },
    { "word": "but", "meaning": "কিন্তু", "pronunciation": "বাট" },
    { "word": "or", "meaning": "অথবা", "pronunciation": "অর" },
    { "word": "because", "meaning": "কারণ", "pronunciation": "বিকজ" },
    { "word": "so", "meaning": "তাই", "pronunciation": "সো" },
    { "word": "although", "meaning": "যদিও", "pronunciation": "অলদো" },
    { "word": "if", "meaning": "যদি", "pronunciation": "ইফ" },
    { "word": "since", "meaning": "যেহেতু", "pronunciation": "সিন্স" },
    { "word": "while", "meaning": "যখন", "pronunciation": "হোয়াইল" },
    { "word": "until", "meaning": "যতক্ষণ না", "pronunciation": "আনটিল" },
    { "word": "unless", "meaning": "যদি না", "pronunciation": "আনলেস" },
    { "word": "whether", "meaning": "যদি", "pronunciation": "হোয়েদার" },
    { "word": "yet", "meaning": "তবুও", "pronunciation": "ইয়েট" },
    { "word": "either", "meaning": "অথবা", "pronunciation": "আইদার" },
    { "word": "neither", "meaning": "না এই, না ঐ", "pronunciation": "নিদার" },
    { "word": "wow", "meaning": "বাহ", "pronunciation": "ওয়াও" },
    { "word": "ouch", "meaning": "আহ", "pronunciation": "আউচ" },
    { "word": "oops", "meaning": "উফ", "pronunciation": "উপস" },
    { "word": "hey", "meaning": "এই", "pronunciation": "হে" },
    { "word": "oh", "meaning": "ওহ", "pronunciation": "ও" },
    { "word": "ah", "meaning": "আহা", "pronunciation": "আ" },
    { "word": "alas", "meaning": "হায়", "pronunciation": "অ্যালাস" },
    { "word": "hurrah", "meaning": "হুরrah", "pronunciation": "হুরrah" },
    { "word": "bravo", "meaning": "শাবাশ", "pronunciation": "ব্রাভো" },
    { "word": "ugh", "meaning": "ধুর", "pronunciation": "আগ" },
    { "word": "yikes", "meaning": "বিপদ", "pronunciation": "ইয়াইকস" },
    { "word": "shh", "meaning": "চুপ", "pronunciation": "শ্" },
    { "word": "yay", "meaning": "ইয়েহ", "pronunciation": "ইয়েহ" },
    { "word": "hurray", "meaning": "হুরrah", "pronunciation": "হুরrah" },
    { "word": "hmm", "meaning": "হুম", "pronunciation": "হুম" },
    { "word": "head", "meaning": "মাথা", "pronunciation": "হেড" },
    { "word": "eye", "meaning": "চোখ", "pronunciation": "আই" },
    { "word": "ear", "meaning": "কান", "pronunciation": "ইয়ার" },
    { "word": "nose", "meaning": "নাক", "pronunciation": "নোজ" },
    { "word": "mouth", "meaning": "মুখ", "pronunciation": "মাউথ" },
    { "word": "hand", "meaning": "হাত", "pronunciation": "হ্যান্ড" },
    { "word": "leg", "meaning": "পা", "pronunciation": "লেগ" },
    { "word": "foot", "meaning": "পায়ের পাতা", "pronunciation": "ফুট" },
    { "word": "heart", "meaning": "হৃদয়", "pronunciation": "হার্ট" },
    { "word": "brain", "meaning": "মস্তিষ্ক", "pronunciation": "ব্রেইন" },
    { "word": "stomach", "meaning": "পেট", "pronunciation": "স্টমাক" },
    { "word": "arm", "meaning": "বাহু", "pronunciation": "আর্ম" },
    { "word": "finger", "meaning": "আঙুল", "pronunciation": "ফিঙ্গার" },
    { "word": "tooth", "meaning": "দাঁত", "pronunciation": "টুথ" },
    { "word": "skin", "meaning": "ত্বক", "pronunciation": "স্কিন" },
    { "word": "bone", "meaning": "হাড়", "pronunciation": "বোন" },
    { "word": "blood", "meaning": "রক্ত", "pronunciation": "ব্লাড" },
    { "word": "lung", "meaning": "ফুসফুস", "pronunciation": "লাং" },
    { "word": "kidney", "meaning": "বৃক্ক", "pronunciation": "কিডনি" },
    { "word": "liver", "meaning": "যকৃত", "pronunciation": "লিভার" },
    { "word": "kind", "meaning": "দয়ালু", "pronunciation": "কাইন্ড" },
    { "word": "honest", "meaning": "সৎ", "pronunciation": "অনেস্ট" },
    { "word": "brave", "meaning": "সাহসী", "pronunciation": "ব্রেভ" },
    { "word": "patient", "meaning": "ধৈর্যশীল", "pronunciation": "পেশেন্ট" },
    { "word": "humble", "meaning": "নম্র", "pronunciation": "হাম্বল" },
    { "word": "polite", "meaning": "ভদ্র", "pronunciation": "পোলাইট" },
    { "word": "generous", "meaning": "উদার", "pronunciation": "জেনারাস" },
    { "word": "intelligent", "meaning": "বুদ্ধিমান", "pronunciation": "ইন্টেলিজেন্ট" },
    { "word": "loyal", "meaning": "বিশ্বস্ত", "pronunciation": "লয়াল" },
    { "word": "friendly", "meaning": "বন্ধুভাবাপন্ন", "pronunciation": "ফ্রেন্ডলি" },
    { "word": "responsible", "meaning": "দায়িত্বশীল", "pronunciation": "রেস্পন্সিবল" },
    { "word": "forgiving", "meaning": "ক্ষমাশীল", "pronunciation": "ফরগিভিং" },
    { "word": "creative", "meaning": "সৃজনশীল", "pronunciation": "ক্রিয়েটিভ" },
    { "word": "optimistic", "meaning": "আশাবাদী", "pronunciation": "অপটিমিস্টিক" },
    { "word": "hardworking", "meaning": "পরিশ্রমী", "pronunciation": "হার্ডওয়ার্কিং" },
    { "word": "selfless", "meaning": "নিঃস্বার্থ", "pronunciation": "সেল্ফলেস" },
    { "word": "ambitious", "meaning": "উদ্যমী", "pronunciation": "অ্যাম্বিশাস" },
    { "word": "thoughtful", "meaning": "চিন্তাশীল", "pronunciation": "থটফুল" },
    { "word": "cheerful", "meaning": "প্রফুল্ল", "pronunciation": "চিয়ারফুল" },
    { "word": "compassionate", "meaning": "সহানুভূতিশীল", "pronunciation": "কমপ্যাশনেট" },
    { "word": "human", "meaning": "মানব", "pronunciation": "হিউম্যান" },
    { "word": "society", "meaning": "সমাজ", "pronunciation": "সোসাইটি" },
    { "word": "civilization", "meaning": "সভ্যতা", "pronunciation": "সিভিলাইজেশন" },
    { "word": "culture", "meaning": "সংস্কৃতি", "pronunciation": "কালচার" },
    { "word": "community", "meaning": "সম্প্রদায়", "pronunciation": "কমিউনিটি" },
    { "word": "race", "meaning": "জাতি", "pronunciation": "রেস" },
    { "word": "ethnicity", "meaning": "জাতিগত পরিচয়", "pronunciation": "এথনিসিটি" },
    { "word": "humanity", "meaning": "মানবতা", "pronunciation": "হিউম্যানিটি" },
    { "word": "freedom", "meaning": "স্বাধীনতা", "pronunciation": "ফ্রিডম" },
    { "word": "justice", "meaning": "ন্যায়বিচার", "pronunciation": "জাস্টিস" },
    { "word": "equality", "meaning": "সমতা", "pronunciation": "ইক্যুয়ালিটি" },
    { "word": "peace", "meaning": "শান্তি", "pronunciation": "পিস" },
    { "word": "brotherhood", "meaning": "ভ্রাতৃত্ব", "pronunciation": "ব্রাদারহুড" },
    { "word": "charity", "meaning": "দাতব্য", "pronunciation": "চারিটি" },
    { "word": "diversity", "meaning": "বৈচিত্র্য", "pronunciation": "ডাইভারসিটি" },
    { "word": "democracy", "meaning": "গণতন্ত্র", "pronunciation": "ডেমোক্র্যাসি" },
    { "word": "human rights", "meaning": "মানবাধিকার", "pronunciation": "হিউম্যান রাইটস" },
    { "word": "dignity", "meaning": "মর্যাদা", "pronunciation": "ডিগনিটি" },
    { "word": "cooperation", "meaning": "সহযোগিতা", "pronunciation": "কোঅপারেশন" },
    { "word": "compassion", "meaning": "সহানুভূতি", "pronunciation": "কমপ্যাশন" },
    { "word": "father", "meaning": "বাবা", "pronunciation": "ফাদার" },
    { "word": "mother", "meaning": "মা", "pronunciation": "মাদার" },
    { "word": "brother", "meaning": "ভাই", "pronunciation": "ব্রাদার" },
    { "word": "sister", "meaning": "বোন", "pronunciation": "সিস্টার" },
    { "word": "grandfather", "meaning": "দাদু", "pronunciation": "গ্র্যান্ডফাদার" },
    { "word": "grandmother", "meaning": "ঠাকুরমা", "pronunciation": "গ্র্যান্ডমাদার" },
    { "word": "uncle", "meaning": "কাকা / মামা", "pronunciation": "আঙ্কল" },
    { "word": "aunt", "meaning": "কাকিমা / মাসি", "pronunciation": "আন্ট" },
    { "word": "cousin", "meaning": "চাচাতো ভাই / বোন", "pronunciation": "কাজিন" },
    { "word": "nephew", "meaning": "ভাইপো", "pronunciation": "নেফিউ" },
    { "word": "niece", "meaning": "ভাইঝি", "pronunciation": "নিজ" },
    { "word": "husband", "meaning": "স্বামী", "pronunciation": "হাজব্যান্ড" },
    { "word": "wife", "meaning": "স্ত্রী", "pronunciation": "ওয়াইফ" },
    { "word": "son", "meaning": "ছেলে", "pronunciation": "সন" },
    { "word": "daughter", "meaning": "মেয়ে", "pronunciation": "ডটার" },
    { "word": "father-in-law", "meaning": "শ্বশুর", "pronunciation": "ফাদার-ইন-ল" },
    { "word": "mother-in-law", "meaning": "শাশুড়ি", "pronunciation": "মাদার-ইন-ল" },
    { "word": "brother-in-law", "meaning": "ভাই-জামাই", "pronunciation": "ব্রাদার-ইন-ল" },
    { "word": "sister-in-law", "meaning": "বোন-জামাই", "pronunciation": "সিস্টার-ইন-ল" },
    { "word": "grandson", "meaning": "নাতি", "pronunciation": "গ্র্যান্ডসন" },
    { "word": "granddaughter", "meaning": "নাতনি", "pronunciation": "গ্র্যান্ডডটার" },
    { "word": "shirt", "meaning": "শার্ট", "pronunciation": "শার্ট" },
    { "word": "pants", "meaning": "প্যান্ট", "pronunciation": "প্যান্টস" },
    { "word": "dress", "meaning": "পোশাক", "pronunciation": "ড্রেস" },
    { "word": "skirt", "meaning": "স্কার্ট", "pronunciation": "স্কার্ট" },
    { "word": "jacket", "meaning": "জ্যাকেট", "pronunciation": "জ্যাকেট" },
    { "word": "suit", "meaning": "সুট", "pronunciation": "সুট" },
    { "word": "tie", "meaning": "টাই", "pronunciation": "টাই" },
    { "word": "saree", "meaning": "শাড়ি", "pronunciation": "সারি" },
    { "word": "kurta", "meaning": "কুর্তা", "pronunciation": "কুর্তা" },
    { "word": "blouse", "meaning": "ব্লাউজ", "pronunciation": "ব্লাউজ" },
    { "word": "shoes", "meaning": "জুতো", "pronunciation": "শুজ" },
    { "word": "sandals", "meaning": "স্যান্ডেল", "pronunciation": "স্যান্ডালস" },
    { "word": "hat", "meaning": "টুপি", "pronunciation": "হ্যাট" },
    { "word": "scarf", "meaning": "স্কার্ফ", "pronunciation": "স্কার্ফ" },
    { "word": "gloves", "meaning": "দস্তানা", "pronunciation": "গ্লোভস" },
    { "word": "belt", "meaning": "বেল্ট", "pronunciation": "বেল্ট" },
    { "word": "shorts", "meaning": "ছোট প্যান্ট", "pronunciation": "শর্টস" },
    { "word": "jeans", "meaning": "জিন্স", "pronunciation": "জিন্স" },
    { "word": "t-shirt", "meaning": "টি-শার্ট", "pronunciation": "টি-শার্ট" },
    { "word": "socks", "meaning": "মোজা", "pronunciation": "সকস" },
    { "word": "school", "meaning": "স্কুল", "pronunciation": "স্কুল" },
    { "word": "college", "meaning": "কলেজ", "pronunciation": "কলেজ" },
    { "word": "university", "meaning": "বিশ্ববিদ্যালয়", "pronunciation": "ইউনিভার্সিটি" },
    { "word": "teacher", "meaning": "শিক্ষক", "pronunciation": "টিচার" },
    { "word": "student", "meaning": "ছাত্র", "pronunciation": "স্টুডেন্ট" },
    { "word": "classroom", "meaning": "শ্রেণীকক্ষ", "pronunciation": "ক্লাসরুম" },
    { "word": "homework", "meaning": "বাড়ির কাজ", "pronunciation": "হোমওয়ার্ক" },
    { "word": "exam", "meaning": "পরীক্ষা", "pronunciation": "এক্সাম" },
    { "word": "subject", "meaning": "বিষয়", "pronunciation": "সাবজেক্ট" },
    { "word": "book", "meaning": "বই", "pronunciation": "বুক" },
    { "word": "notebook", "meaning": "নোটবই", "pronunciation": "নোটবুক" },
    { "word": "pen", "meaning": "কলম", "pronunciation": "পেন" },
    { "word": "pencil", "meaning": "পেন্সিল", "pronunciation": "পেন্সিল" },
    { "word": "blackboard", "meaning": "কালো বোর্ড", "pronunciation": "ব্ল্যাকবোর্ড" },
    { "word": "library", "meaning": "গ্রন্থাগার", "pronunciation": "লাইব্রেরি" },
    { "word": "scholarship", "meaning": "বৃত্তি", "pronunciation": "স্কলারশিপ" },
    { "word": "lecture", "meaning": "বক্তৃতা", "pronunciation": "লেকচার" },
    { "word": "assignment", "meaning": "নির্ধারিত কাজ", "pronunciation": "অ্যাসাইনমেন্ট" },
    { "word": "degree", "meaning": "ডিগ্রি", "pronunciation": "ডিগ্রি" },
    { "word": "certificate", "meaning": "সনদ", "pronunciation": "সার্টিফিকেট" },
    { "word": "doctor", "meaning": "ডাক্তার", "pronunciation": "ডক্টর" },
    { "word": "teacher", "meaning": "শিক্ষক", "pronunciation": "টিচার" },
    { "word": "engineer", "meaning": "প্রকৌশলী", "pronunciation": "ইঞ্জিনিয়ার" },
    { "word": "lawyer", "meaning": "আইনজীবী", "pronunciation": "লয়্যার" },
    { "word": "nurse", "meaning": "নার্স", "pronunciation": "নার্স" },
    { "word": "police officer", "meaning": "পুলিশ কর্মকর্তা", "pronunciation": "পুলিশ অফিসার" },
    { "word": "chef", "meaning": "রাঁধুনি", "pronunciation": "শেফ" },
    { "word": "farmer", "meaning": "কৃষক", "pronunciation": "ফার্মার" },
    { "word": "pilot", "meaning": "পাইলট", "pronunciation": "পাইলট" },
    { "word": "artist", "meaning": "শিল্পী", "pronunciation": "আর্টিস্ট" },
    { "word": "journalist", "meaning": "সাংবাদিক", "pronunciation": "জার্নালিস্ট" },
    { "word": "businessperson", "meaning": "ব্যবসায়ী", "pronunciation": "বিজনেসপার্সন" },
    { "word": "scientist", "meaning": "বিজ্ঞানী", "pronunciation": "সায়েন্টিস্ট" },
    { "word": "writer", "meaning": "লেখক", "pronunciation": "রাইটার" },
    { "word": "driver", "meaning": "চালক", "pronunciation": "ড্রাইভার" },
    { "word": "actor", "meaning": "অভিনেতা", "pronunciation": "অ্যাক্টর" },
    { "word": "architect", "meaning": "স্থপতি", "pronunciation": "আর্কিটেক্ট" },
    { "word": "carpenter", "meaning": "ছুতার", "pronunciation": "কার্পেন্টার" },
    { "word": "electrician", "meaning": "বিদ্যুৎকর্মী", "pronunciation": "ইলেক্ট্রিশিয়ান" },
    { "word": "plumber", "meaning": "প্লাম্বার", "pronunciation": "প্লাম্বার" },
    { "word": "mechanic", "meaning": "মিস্ত্রি", "pronunciation": "মেকানিক" },
    { "word": "banker", "meaning": "ব্যাংকার", "pronunciation": "ব্যাংকার" },
    { "word": "dentist", "meaning": "দন্তচিকিৎসক", "pronunciation": "ডেন্টিস্ট" },
    { "word": "pharmacist", "meaning": "ওষুধ প্রস্তুতকারক", "pronunciation": "ফার্মাসিস্ট" },
    { "word": "soldier", "meaning": "সৈনিক", "pronunciation": "সোলজার" },
    { "word": "firefighter", "meaning": "দমকলকর্মী", "pronunciation": "ফায়ারফাইটার" },
    { "word": "judge", "meaning": "বিচারক", "pronunciation": "জাজ" },
    { "word": "politician", "meaning": "রাজনীতিবিদ", "pronunciation": "পলিটিশিয়ান" },
    { "word": "accountant", "meaning": "হিসাবরক্ষক", "pronunciation": "অ্যাকাউন্ট্যান্ট" },
    { "word": "manager", "meaning": "ব্যবস্থাপক", "pronunciation": "ম্যানেজার" },
    { "word": "librarian", "meaning": "গ্রন্থাগারিক", "pronunciation": "লাইব্রেরিয়ান" },
    { "word": "receptionist", "meaning": "সংবর্ধক", "pronunciation": "রিসেপশনিস্ট" },
    { "word": "tailor", "meaning": "দর্জি", "pronunciation": "টেইলার" },
    { "word": "photographer", "meaning": "ছবিয়াল", "pronunciation": "ফটোগ্রাফার" },
    { "word": "veterinarian", "meaning": "পশুচিকিৎসক", "pronunciation": "ভেটেরিনেরিয়ান" },
    { "word": "bartender", "meaning": "মদ পরিবেশনকারী", "pronunciation": "বারটেন্ডার" },
    { "word": "waiter", "meaning": "ওয়েটার", "pronunciation": "ওয়েটার" },
    { "word": "apple", "meaning": "আপেল", "pronunciation": "অ্যাপল" },
    { "word": "banana", "meaning": "কলা", "pronunciation": "ব্যানানা" },
    { "word": "bread", "meaning": "রুটি", "pronunciation": "ব্রেড" },
    { "word": "rice", "meaning": "ভাত", "pronunciation": "রাইস" },
    { "word": "water", "meaning": "পানি", "pronunciation": "ওয়াটার" },
    { "word": "milk", "meaning": "দুধ", "pronunciation": "মিল্ক" },
    { "word": "orange", "meaning": "কমলা", "pronunciation": "অরেঞ্জ" },
    { "word": "grape", "meaning": "আঙুর", "pronunciation": "গ্রেপ" },
    { "word": "mango", "meaning": "আম", "pronunciation": "ম্যাঙ্গো" },
    { "word": "potato", "meaning": "আলু", "pronunciation": "পোটেটো" },
    { "word": "tomato", "meaning": "টমেটো", "pronunciation": "টোম্যাটো" },
    { "word": "chicken", "meaning": "মুরগির মাংস", "pronunciation": "চিকেন" },
    { "word": "fish", "meaning": "মাছ", "pronunciation": "ফিশ" },
    { "word": "egg", "meaning": "ডিম", "pronunciation": "এগ" },
    { "word": "butter", "meaning": "মাখন", "pronunciation": "বাটার" },
    { "word": "cheese", "meaning": "পনির", "pronunciation": "চিজ" },
    { "word": "carrot", "meaning": "গাজর", "pronunciation": "ক্যারট" },
    { "word": "onion", "meaning": "পেঁয়াজ", "pronunciation": "অনিয়ন" },
    { "word": "salt", "meaning": "লবণ", "pronunciation": "সল্ট" },
    { "word": "sugar", "meaning": "চিনি", "pronunciation": "শুগার" },
    { "word": "pepper", "meaning": "গোলমরিচ", "pronunciation": "পেপার" },
    { "word": "tea", "meaning": "চা", "pronunciation": "টি" },
    { "word": "coffee", "meaning": "কফি", "pronunciation": "কফি" },
    { "word": "juice", "meaning": "রস", "pronunciation": "জুস" },
    { "word": "wine", "meaning": "মদ", "pronunciation": "ওয়াইন" },
    { "word": "soda", "meaning": "সোডা", "pronunciation": "সোডা" },
    { "word": "cake", "meaning": "কেক", "pronunciation": "কেক" },
    { "word": "ice cream", "meaning": "আইসক্রিম", "pronunciation": "আইসক্রিম" },
    { "word": "chocolate", "meaning": "চকলেট", "pronunciation": "চকলেট" },
    { "word": "pasta", "meaning": "পাস্তা", "pronunciation": "পাস্তা" },
    { "word": "pizza", "meaning": "পিজা", "pronunciation": "পিজা" },
    { "word": "sandwich", "meaning": "স্যান্ডউইচ", "pronunciation": "স্যান্ডউইচ" },
    { "word": "burger", "meaning": "বার্গার", "pronunciation": "বার্গার" },
    { "word": "fries", "meaning": "ফ্রাই", "pronunciation": "ফ্রাইস" },
    { "word": "soup", "meaning": "সুপ", "pronunciation": "সুপ" },
    { "word": "noodles", "meaning": "নুডলস", "pronunciation": "নুডলস" },
    { "word": "beef", "meaning": "গরুর মাংস", "pronunciation": "বিফ" },
    { "word": "pork", "meaning": "শূকরের মাংস", "pronunciation": "পর্ক" },
    { "word": "lamb", "meaning": "ভেড়ার মাংস", "pronunciation": "ল্যাম্ব" },
    { "word": "shrimp", "meaning": "চিংড়ি", "pronunciation": "শ্রিম্প" },
    { "word": "salad", "meaning": "সালাদ", "pronunciation": "সালাদ" },
    { "word": "gravy", "meaning": "ঝোল", "pronunciation": "গ্রেভি" },
    { "word": "biscuit", "meaning": "বিস্কুট", "pronunciation": "বিস্কিট" },
    { "word": "honey", "meaning": "মধু", "pronunciation": "হানি" },
    { "word": "jam", "meaning": "জ্যাম", "pronunciation": "জ্যাম" },
    { "word": "potato", "meaning": "আলু", "pronunciation": "পোটেটো" },
    { "word": "tomato", "meaning": "টমেটো", "pronunciation": "টোম্যাটো" },
    { "word": "onion", "meaning": "পেঁয়াজ", "pronunciation": "অনিয়ন" },
    { "word": "garlic", "meaning": "রসুন", "pronunciation": "গার্লিক" },
    { "word": "carrot", "meaning": "গাজর", "pronunciation": "ক্যারট" },
    { "word": "cabbage", "meaning": "বাঁধাকপি", "pronunciation": "ক্যাবেজ" },
    { "word": "cauliflower", "meaning": "ফুলকপি", "pronunciation": "কাউলিফ্লাওয়ার" },
    { "word": "spinach", "meaning": "পালং শাক", "pronunciation": "স্পিনাচ" },
    { "word": "broccoli", "meaning": "ব্রোকলি", "pronunciation": "ব্রোকলি" },
    { "word": "peas", "meaning": "মটরশুটি", "pronunciation": "পিস" },
    { "word": "eggplant", "meaning": "বেগুন", "pronunciation": "এগপ্লান্ট" },
    { "word": "cucumber", "meaning": "শসা", "pronunciation": "কিউকাম্বার" },
    { "word": "pumpkin", "meaning": "কুমড়া", "pronunciation": "পাম্পকিন" },
    { "word": "radish", "meaning": "মূলা", "pronunciation": "র্যাডিশ" },
    { "word": "beetroot", "meaning": "বিট", "pronunciation": "বিটরুট" },
    { "word": "okra", "meaning": "ঢেঁড়স", "pronunciation": "ওকরা" },
    { "word": "bitter gourd", "meaning": "করলা", "pronunciation": "বিটার গার্ড" },
    { "word": "zucchini", "meaning": "জুচিনি", "pronunciation": "জুচিনি" },
    { "word": "bell pepper", "meaning": "ক্যাপসিকাম", "pronunciation": "বেল পেপার" },
    { "word": "sweet potato", "meaning": "মিষ্টি আলু", "pronunciation": "সুইট পোটেটো" },
    { "word": "lettuce", "meaning": "লেটুস", "pronunciation": "লেটুস" },
    { "word": "green beans", "meaning": "সবুজ শিম", "pronunciation": "গ্রিন বিনস" },
    { "word": "mushroom", "meaning": "মাশরুম", "pronunciation": "মাশরুম" },
    { "word": "ginger", "meaning": "আদা", "pronunciation": "জিঞ্জার" },
    { "word": "turnip", "meaning": "শালগম", "pronunciation": "টার্নিপ" },
    { "word": "coriander", "meaning": "ধনেপাতা", "pronunciation": "করিয়েন্ডার" },
    { "word": "parsley", "meaning": "পার্সলি", "pronunciation": "পার্সলি" },
    { "word": "chili", "meaning": "মরিচ", "pronunciation": "চিলি" },
    { "word": "fenugreek", "meaning": "মেথি", "pronunciation": "ফেনুগ্রিক" },
    { "word": "basil", "meaning": "তুলসি", "pronunciation": "বেসিল" },
    { "word": "mint", "meaning": "পুদিনা", "pronunciation": "মিন্ট" },
    { "word": "apple", "meaning": "আপেল", "pronunciation": "অ্যাপল" },
    { "word": "banana", "meaning": "কলা", "pronunciation": "ব্যানানা" },
    { "word": "orange", "meaning": "কমলা", "pronunciation": "অরেঞ্জ" },
    { "word": "mango", "meaning": "আম", "pronunciation": "ম্যাঙ্গো" },
    { "word": "grape", "meaning": "আঙুর", "pronunciation": "গ্রেপ" },
    { "word": "pineapple", "meaning": "আনারস", "pronunciation": "পাইনঅ্যাপল" },
    { "word": "watermelon", "meaning": "তরমুজ", "pronunciation": "ওয়াটারমেলন" },
    { "word": "strawberry", "meaning": "স্ট্রবেরি", "pronunciation": "স্ট্রবেরি" },
    { "word": "pear", "meaning": "নাশপাতি", "pronunciation": "পিয়ার" },
    { "word": "cherry", "meaning": "চেরি", "pronunciation": "চেরি" },
    { "word": "peach", "meaning": "পিচ", "pronunciation": "পিচ" },
    { "word": "plum", "meaning": "বরই", "pronunciation": "প্লাম" },
    { "word": "papaya", "meaning": "পেঁপে", "pronunciation": "পাপায়া" },
    { "word": "pomegranate", "meaning": "ডালিম", "pronunciation": "পোমেগ্রানেট" },
    { "word": "lemon", "meaning": "লেবু", "pronunciation": "লেমন" },
    { "word": "lime", "meaning": "কাগজি লেবু", "pronunciation": "লাইম" },
    { "word": "kiwi", "meaning": "কিউই", "pronunciation": "কিউই" },
    { "word": "guava", "meaning": "পেয়ারা", "pronunciation": "গুয়াভা" },
    { "word": "jackfruit", "meaning": "কাঁঠাল", "pronunciation": "জ্যাকফ্রুট" },
    { "word": "lychee", "meaning": "লিচু", "pronunciation": "লিচি" },
    { "word": "coconut", "meaning": "নারকেল", "pronunciation": "কোকোনাট" },
    { "word": "fig", "meaning": "ডুমুর", "pronunciation": "ফিগ" },
    { "word": "blueberry", "meaning": "ব্লুবেরি", "pronunciation": "ব্লুবেরি" },
    { "word": "raspberry", "meaning": "রাস্পবেরি", "pronunciation": "রাস্পবেরি" },
    { "word": "blackberry", "meaning": "ব্ল্যাকবেরি", "pronunciation": "ব্ল্যাকবেরি" },
    { "word": "apricot", "meaning": "খুবানি", "pronunciation": "অ্যাপ্রিকট" },
    { "word": "grapefruit", "meaning": "জাম্বুরা", "pronunciation": "গ্রেপফ্রুট" },
    { "word": "melon", "meaning": "ফুটি", "pronunciation": "মেলন" },
    { "word": "custard apple", "meaning": "আতা", "pronunciation": "কাস্টার্ড অ্যাপল" },
    { "word": "durian", "meaning": "ডুরিয়ান", "pronunciation": "ডুরিয়ান" },
    { "word": "dragon fruit", "meaning": "ড্রাগন ফল", "pronunciation": "ড্রাগন ফ্রুট" },
    { "word": "star fruit", "meaning": "কামরাঙ্গা", "pronunciation": "স্টার ফ্রুট" },
    { "word": "passion fruit", "meaning": "প্যাশন ফল", "pronunciation": "প্যাশন ফ্রুট" },
    { "word": "date", "meaning": "খেজুর", "pronunciation": "ডেট" },
    { "word": "cranberry", "meaning": "ক্র্যানবেরি", "pronunciation": "ক্র্যানবেরি" },
    { "word": "olive", "meaning": "জলপাই", "pronunciation": "অলিভ" },
    { "word": "tamarind", "meaning": "তেঁতুল", "pronunciation": "ট্যামারিন্ড" },
    { "word": "avocado", "meaning": "অ্যাভোকাডো", "pronunciation": "অ্যাভোকাডো" },
    { "word": "gooseberry", "meaning": "আমলকি", "pronunciation": "গুজবেরি" },
    { "word": "rose", "meaning": "গোলাপ", "pronunciation": "রোজ" },
    { "word": "lotus", "meaning": "পদ্ম", "pronunciation": "লোটাস" },
    { "word": "sunflower", "meaning": "সূর্যমুখী", "pronunciation": "সানফ্লাওয়ার" },
    { "word": "jasmine", "meaning": "জুঁই", "pronunciation": "জ্যাসমিন" },
    { "word": "marigold", "meaning": "গাঁদা ফুল", "pronunciation": "ম্যারিগোল্ড" },
    { "word": "tulip", "meaning": "টিউলিপ", "pronunciation": "টিউলিপ" },
    { "word": "hibiscus", "meaning": "জবা ফুল", "pronunciation": "হিবিস্কাস" },
    { "word": "daisy", "meaning": "ডেজি", "pronunciation": "ডেজি" },
    { "word": "orchid", "meaning": "অর্কিড", "pronunciation": "অর্কিড" },
    { "word": "lily", "meaning": "লিলি", "pronunciation": "লিলি" },
    { "word": "chrysanthemum", "meaning": "চন্দ্রমল্লিকা", "pronunciation": "ক্রাইসান্থেমাম" },
    { "word": "bougainvillea", "meaning": "বোগেনভিলিয়া", "pronunciation": "বোগেনভিলিয়া" },
    { "word": "magnolia", "meaning": "চম্পা ফুল", "pronunciation": "ম্যাগনোলিয়া" },
    { "word": "poppy", "meaning": "আফিম ফুল", "pronunciation": "পপি" },
    { "word": "dahlia", "meaning": "ডালিয়া", "pronunciation": "ডালিয়া" },
    { "word": "geranium", "meaning": "জেরানিয়াম", "pronunciation": "জেরানিয়াম" },
    { "word": "lavender", "meaning": "ল্যাভেন্ডার", "pronunciation": "ল্যাভেন্ডার" },
    { "word": "carnation", "meaning": "কার্নেশন", "pronunciation": "কার্নেশন" },
    { "word": "azalea", "meaning": "আজেলিয়া", "pronunciation": "আজেলিয়া" },
    { "word": "freesia", "meaning": "ফ্রেসিয়া", "pronunciation": "ফ্রেসিয়া" },
    { "word": "violet", "meaning": "বেগুনি ফুল", "pronunciation": "ভায়োলেট" },
    { "word": "narcissus", "meaning": "নার্সিসাস", "pronunciation": "নার্সিসাস" },
    { "word": "petunia", "meaning": "পেটুনিয়া", "pronunciation": "পেটুনিয়া" },
    { "word": "plumeria", "meaning": "চাম্পা ফুল", "pronunciation": "প্লুমেরিয়া" },
    { "word": "zinnia", "meaning": "জিনিয়া", "pronunciation": "জিনিয়া" },
    { "word": "wow", "meaning": "বাহ", "pronunciation": "ওয়াও" },
    { "word": "oops", "meaning": "উফ", "pronunciation": "উপ্স" },
    { "word": "ouch", "meaning": "আহ", "pronunciation": "আউচ" },
    { "word": "hey", "meaning": "এই", "pronunciation": "হে" },
    { "word": "oh", "meaning": "ওহ", "pronunciation": "ওহ" },
    { "word": "alas", "meaning": "হায়", "pronunciation": "আলাস" },
    { "word": "aha", "meaning": "আহা", "pronunciation": "আহা" },
    { "word": "bravo", "meaning": "শাবাশ", "pronunciation": "ব্রাভো" },
    { "word": "yikes", "meaning": "বাহ", "pronunciation": "ইয়াইকস" },
    { "word": "hurray", "meaning": "হুররে", "pronunciation": "হুররে" },
    { "word": "phew", "meaning": "উফ", "pronunciation": "ফিউ" },
    { "word": "yippee", "meaning": "ইয়াহু", "pronunciation": "ইপ্পি" },
    { "word": "uh-oh", "meaning": "ওফ", "pronunciation": "আহ ওহ" },
    { "word": "eek", "meaning": "ইক", "pronunciation": "ইক" },
    { "word": "gosh", "meaning": "ওহ্", "pronunciation": "গশ" },
    { "word": "yay", "meaning": "ইয়ে", "pronunciation": "ইয়ে" },
    { "word": "shh", "meaning": "চুপ", "pronunciation": "শ" },
    { "word": "ahem", "meaning": "অ্যাহেম", "pronunciation": "অ্যাহেম" },
    { "word": "yawn", "meaning": "হাই", "pronunciation": "ইয়ন" },
    { "word": "hmm", "meaning": "হুম", "pronunciation": "হুম" },
    { "word": "ugh", "meaning": "ইস", "pronunciation": "উঘ" },
    { "word": "whoa", "meaning": "ওহে", "pronunciation": "ওহো" },
    { "word": "tsk-tsk", "meaning": "অসন্তোষসূচক শব্দ", "pronunciation": "টস্ক-টস্ক" },
    { "word": "yoo-hoo", "meaning": "ইউ-হু", "pronunciation": "ইউ-হু" },
    { "word": "hallelujah", "meaning": "আল্লেলুয়া", "pronunciation": "হাল্লেলুয়া" },
    { "word": "huh", "meaning": "হুঁ", "pronunciation": "হুহ" },
    { "word": "and", "meaning": "এবং", "pronunciation": "অ্যান্ড" },
    { "word": "but", "meaning": "কিন্তু", "pronunciation": "বাট" },
    { "word": "or", "meaning": "অথবা", "pronunciation": "অর" },
    { "word": "because", "meaning": "কারণ", "pronunciation": "বিকজ" },
    { "word": "so", "meaning": "তাই", "pronunciation": "সো" },
    { "word": "although", "meaning": "যদিও", "pronunciation": "অলথো" },
    { "word": "if", "meaning": "যদি", "pronunciation": "ইফ" },
    { "word": "unless", "meaning": "যদি না", "pronunciation": "আনলেস" },
    { "word": "since", "meaning": "যেহেতু", "pronunciation": "সিন্স" },
    { "word": "while", "meaning": "যখন", "pronunciation": "ওয়াইল" },
    { "word": "until", "meaning": "যতক্ষণ না", "pronunciation": "আনটিল" },
    { "word": "though", "meaning": "যদিও", "pronunciation": "থো" },
    { "word": "yet", "meaning": "তবু", "pronunciation": "ইয়েট" },
    { "word": "nor", "meaning": "না", "pronunciation": "নর" },
    { "word": "for", "meaning": "কারণ", "pronunciation": "ফর" },
    { "word": "either", "meaning": "অথবা", "pronunciation": "আইদার" },
    { "word": "neither", "meaning": "না", "pronunciation": "নাইদার" },
    { "word": "as", "meaning": "যেমন", "pronunciation": "অ্যাজ" },
    { "word": "both", "meaning": "উভয়", "pronunciation": "বোথ" },
    { "word": "whether", "meaning": "যাই হোক", "pronunciation": "হয়" },
    { "word": "as if", "meaning": "যেন", "pronunciation": "অ্যাজ ইফ" },
    { "word": "provided", "meaning": "যদি", "pronunciation": "প্রোভাইডেড" },
    { "word": "so that", "meaning": "যাতে", "pronunciation": "সো দ্যাট" },
    { "word": "as well as", "meaning": "এছাড়াও", "pronunciation": "অ্যাজ ওয়েল অ্যাজ" },
    { "word": "in case", "meaning": "যদি", "pronunciation": "ইন কেস" },
    { "word": "even though", "meaning": "যদিও", "pronunciation": "ইভেন থো" },
    { "word": "even if", "meaning": "যদিও", "pronunciation": "ইভেন ইফ" },
    { "word": "rather than", "meaning": "বরং", "pronunciation": "রাদার দ্যান" },
    { "word": "hello", "meaning": "হ্যালো", "pronunciation": "হ্যালো" },
    { "word": "goodbye", "meaning": "বিদায়", "pronunciation": "গুডবাই" },
    { "word": "please", "meaning": "দয়া করে", "pronunciation": "প্লিজ" },
    { "word": "thanks", "meaning": "ধন্যবাদ", "pronunciation": "থ্যাংকস" },
    { "word": "sorry", "meaning": "মাফ", "pronunciation": "সরি" },
    { "word": "yes", "meaning": "হ্যাঁ", "pronunciation": "ইয়েস" },
    { "word": "no", "meaning": "না", "pronunciation": "নো" },
    { "word": "excuse", "meaning": "মাফ", "pronunciation": "এক্সকিউজ" },
    { "word": "name", "meaning": "নাম", "pronunciation": "নেম" },
    { "word": "help", "meaning": "সাহায্য", "pronunciation": "হেল্প" },
    { "word": "morning", "meaning": "সকাল", "pronunciation": "মর্নিং" },
    { "word": "night", "meaning": "রাত", "pronunciation": "নাইট" },
    { "word": "later", "meaning": "পরে", "pronunciation": "লেটার" },
    { "word": "care", "meaning": "যত্ন", "pronunciation": "কেয়ার" },
    { "word": "hungry", "meaning": "ক্ষুধার্ত", "pronunciation": "হাংগ্রি" },
    { "word": "tired", "meaning": "ক্লান্ত", "pronunciation": "টাইয়ার্ড" },
    { "word": "time", "meaning": "সময়", "pronunciation": "টাইম" },
    { "word": "bathroom", "meaning": "বাথরুম", "pronunciation": "বাথরুম" },
    { "word": "moment", "meaning": "মুহূর্ত", "pronunciation": "মোমেন্ট" },
    { "word": "go", "meaning": "যাওয়া", "pronunciation": "গো" },
    { "word": "know", "meaning": "জানা", "pronunciation": "নো" },
    { "word": "help", "meaning": "সহায়তা", "pronunciation": "হেল্প" },
    { "word": "happen", "meaning": "ঘটা", "pronunciation": "হ্যাপেন" },
    { "word": "airport", "meaning": "বিমানবন্দর", "pronunciation": "এয়ারপোর্ট" },
    { "word": "hotel", "meaning": "হোটেল", "pronunciation": "হোটেল" },
    { "word": "reservation", "meaning": "সংরক্ষণ", "pronunciation": "রেজারভেশন" },
    { "word": "ticket", "meaning": "টিকিট", "pronunciation": "টিকিট" },
    { "word": "passport", "meaning": "পাসপোর্ট", "pronunciation": "পাসপোর্ট" },
    { "word": "visa", "meaning": "ভিসা", "pronunciation": "ভিসা" },
    { "word": "luggage", "meaning": "বিমানবন্দরের ব্যাগ", "pronunciation": "ল্যাগেজ" },
    { "word": "flight", "meaning": "ফ্লাইট", "pronunciation": "ফ্লাইট" },
    { "word": "departure", "meaning": "প্রস্থান", "pronunciation": "ডিপারচার" },
    { "word": "arrival", "meaning": "আগমন", "pronunciation": "এ্যারাইভাল" },
    { "word": "boarding", "meaning": "বোর্ডিং", "pronunciation": "বোর্ডিং" },
    { "word": "gate", "meaning": "গেট", "pronunciation": "গেট" },
    { "word": "customs", "meaning": "কাস্টমস", "pronunciation": "কাস্টমস" },
    { "word": "security", "meaning": "নিরাপত্তা", "pronunciation": "সিকিউরিটি" },
    { "word": "taxi", "meaning": "ট্যাক্সি", "pronunciation": "ট্যাক্সি" },
    { "word": "bus", "meaning": "বাস", "pronunciation": "বাস" },
    { "word": "train", "meaning": "ট্রেন", "pronunciation": "ট্রেন" },
    { "word": "car", "meaning": "গাড়ি", "pronunciation": "কার" },
    { "word": "map", "meaning": "ম্যাপ", "pronunciation": "ম্যাপ" },
    { "word": "guide", "meaning": "গাইড", "pronunciation": "গাইড" },
    { "word": "itinerary", "meaning": "ভ্রমণসূচি", "pronunciation": "আইটিনেরারি" },
    { "word": "adventure", "meaning": "অ্যাডভেঞ্চার", "pronunciation": "অ্যাডভেঞ্চার" },
    { "word": "sightseeing", "meaning": "দর্শন", "pronunciation": "সাইটসিইং" },
    { "word": "museum", "meaning": "মিউজিয়াম", "pronunciation": "মিউজিয়াম" },
    { "word": "beach", "meaning": "সৈকত", "pronunciation": "বিচ" },
    { "word": "tour", "meaning": "ভ্রমণ", "pronunciation": "ট্যুর" },
    { "word": "reservation", "meaning": "সংরক্ষণ", "pronunciation": "রেজারভেশন" },
    { "word": "camping", "meaning": "ক্যাম্পিং", "pronunciation": "ক্যাম্পিং" },
    { "word": "hiking", "meaning": "পাহাড়ে ওঠা", "pronunciation": "হাইকিং" },
    { "word": "backpacking", "meaning": "ব্যাকপ্যাকিং", "pronunciation": "ব্যাকপ্যাকিং" },
    { "word": "tourist", "meaning": "পর্যটক", "pronunciation": "ট্যুরিস্ট" },
    { "word": "local", "meaning": "স্থানীয়", "pronunciation": "লোকাল" },
    { "word": "currency", "meaning": "মুদ্রা", "pronunciation": "কারেন্সি" },
    { "word": "exchange", "meaning": "বদলানো", "pronunciation": "এক্সচেঞ্জ" },
    { "word": "emergency", "meaning": "জরুরি", "pronunciation": "এমারজেন্সি" },
    { "word": "clinic", "meaning": "ক্লিনিক", "pronunciation": "ক্লিনিক" },
    { "word": "hospital", "meaning": "হাসপাতাল", "pronunciation": "হাসপিটাল" },
    { "word": "pharmacy", "meaning": "ফার্মেসি", "pronunciation": "ফার্মেসি" },
    { "word": "restaurant", "meaning": "রেস্টুরেন্ট", "pronunciation": "রেস্টুরেন্ট" },
    { "word": "menu", "meaning": "মেনু", "pronunciation": "মেনু" },
    { "word": "bill", "meaning": "বিল", "pronunciation": "বিল" },
    { "word": "reservation", "meaning": "সংরক্ষণ", "pronunciation": "রেজারভেশন" },
    { "word": "check-in", "meaning": "চেক-ইন", "pronunciation": "চেক-ইন" },
    { "word": "check-out", "meaning": "চেক-আউট", "pronunciation": "চেক-আউট" },
    { "word": "suitcase", "meaning": "সুটকেস", "pronunciation": "সুটকেস" },
    { "word": "backpack", "meaning": "ব্যাকপ্যাক", "pronunciation": "ব্যাকপ্যাক" },
    { "word": "guidebook", "meaning": "গাইডবুক", "pronunciation": "গাইডবুক" },
    { "word": "souvenir", "meaning": "সুভেনির", "pronunciation": "সুভেনির" },
    { "word": "tourist spot", "meaning": "পর্যটক স্থান", "pronunciation": "ট্যুরিস্ট স্পট" },
    { "word": "transport", "meaning": "পরিবহন", "pronunciation": "ট্রান্সপোর্ট" },
    { "word": "route", "meaning": "রুট", "pronunciation": "রুট" },
    { "word": "store", "meaning": "দোকান", "pronunciation": "স্টোর" },
    { "word": "shop", "meaning": "দোকান", "pronunciation": "শপ" },
    { "word": "mall", "meaning": "মল", "pronunciation": "মল" },
    { "word": "market", "meaning": "বাজার", "pronunciation": "মার্কেট" },
    { "word": "purchase", "meaning": "ক্রয়", "pronunciation": "পার্চেস" },
    { "word": "buy", "meaning": "কেনা", "pronunciation": "বাই" },
    { "word": "sell", "meaning": "বিক্রি করা", "pronunciation": "সেল" },
    { "word": "cash", "meaning": "নগদ", "pronunciation": "ক্যাশ" },
    { "word": "credit card", "meaning": "ক্রেডিট কার্ড", "pronunciation": "ক্রেডিট কার্ড" },
    { "word": "debit card", "meaning": "ডেবিট কার্ড", "pronunciation": "ডেবিট কার্ড" },
    { "word": "receipt", "meaning": "রসিদ", "pronunciation": "রিসিপ্ট" },
    { "word": "discount", "meaning": "ছাড়", "pronunciation": "ডিসকাউন্ট" },
    { "word": "price", "meaning": "মূল্য", "pronunciation": "প্রাইস" },
    { "word": "expensive", "meaning": "দামি", "pronunciation": "এক্সপেনসিভ" },
    { "word": "cheap", "meaning": "সস্তা", "pronunciation": "চীপ" },
    { "word": "bargain", "meaning": "দাম দরদাম", "pronunciation": "বাগেন" },
    { "word": "sale", "meaning": "বিক্রি", "pronunciation": "সেল" },
    { "word": "offer", "meaning": "অফার", "pronunciation": "অফার" },
    { "word": "refund", "meaning": "প্রত্যর্পণ", "pronunciation": "রিফান্ড" },
    { "word": "exchange", "meaning": "বদলানো", "pronunciation": "এক্সচেঞ্জ" },
    { "word": "item", "meaning": "বস্তু", "pronunciation": "আইটেম" },
    { "word": "product", "meaning": "পণ্য", "pronunciation": "প্রোডাক্ট" },
    { "word": "size", "meaning": "আকার", "pronunciation": "সাইজ" },
    { "word": "color", "meaning": "রং", "pronunciation": "কালার" },
    { "word": "fit", "meaning": "মাপ", "pronunciation": "ফিট" },
    { "word": "try on", "meaning": "পরখ করা", "pronunciation": "ট্রাই অন" },
    { "word": "fitting room", "meaning": "ফিটিং রুম", "pronunciation": "ফিটিং রুম" },
    { "word": "checkout", "meaning": "চেকআউট", "pronunciation": "চেকআউট" },
    { "word": "shopping bag", "meaning": "শপিং ব্যাগ", "pronunciation": "শপিং ব্যাগ" },
    { "word": "basket", "meaning": "টلة", "pronunciation": "বাস্কেট" },
    { "word": "cart", "meaning": "কার্ট", "pronunciation": "কার্ট" },
    { "word": "shopping list", "meaning": "শপিং লিস্ট", "pronunciation": "শপিং লিস্ট" },
    { "word": "store manager", "meaning": "দোকান ব্যবস্থাপক", "pronunciation": "স্টোর ম্যানেজার" },
    { "word": "salesperson", "meaning": "বিক্রয়কর্মী", "pronunciation": "সেলসপারসন" },
    { "word": "customer", "meaning": "গ্রাহক", "pronunciation": "কাস্টমার" },
    { "word": "service", "meaning": "পরিসেবা", "pronunciation": "সার্ভিস" },
    { "word": "shopping spree", "meaning": "শপিং স্প্রী", "pronunciation": "শপিং স্প্রী" },
    { "word": "receipt", "meaning": "রসিদ", "pronunciation": "রিসিপ্ট" },
    { "word": "bandwidth", "meaning": "ব্যান্ডউইথ", "pronunciation": "ব্যান্ডউইথ" },
    { "word": "firewall", "meaning": "ফায়ারওয়াল", "pronunciation": "ফায়ারওয়াল" },
    { "word": "cookie", "meaning": "কুকি", "pronunciation": "কুকি" },
    { "word": "cache", "meaning": "ক্যাশ", "pronunciation": "ক্যাশ" },
    { "word": "server", "meaning": "সার্ভার", "pronunciation": "সার্ভার" },
    { "word": "protocol", "meaning": "প্রোটোকল", "pronunciation": "প্রোটোকল" },
    { "word": "bandwidth", "meaning": "ব্যান্ডউইথ", "pronunciation": "ব্যান্ডউইথ" },
    { "word": "upload", "meaning": "আপলোড", "pronunciation": "আপলোড" },
    { "word": "download", "meaning": "ডাউনলোড", "pronunciation": "ডাউনলোড" },
    { "word": "debugging", "meaning": "ডিবাগিং", "pronunciation": "ডিবাগিং" },
    { "word": "version", "meaning": "সংস্করণ", "pronunciation": "ভার্সন" },
    { "word": "repository", "meaning": "রিপোজিটরি", "pronunciation": "রিপোজিটরি" },
    { "word": "synchronization", "meaning": "সিঙ্ক্রোনাইজেশন", "pronunciation": "সিঙ্ক্রোনাইজেশন" },
    { "word": "cache", "meaning": "ক্যাশ", "pronunciation": "ক্যাশ" },
    { "word": "interface", "meaning": "ইন্টারফেস", "pronunciation": "ইন্টারফেস" },
    { "word": "API", "meaning": "এপিআই", "pronunciation": "এপিআই" },
    { "word": "server", "meaning": "সার্ভার", "pronunciation": "সার্ভার" },
    { "word": "client", "meaning": "ক্লায়েন্ট", "pronunciation": "ক্লায়েন্ট" },
    { "word": "host", "meaning": "হোস্ট", "pronunciation": "হোস্ট" },
    { "word": "load", "meaning": "লোড", "pronunciation": "লোড" },
    { "word": "throughput", "meaning": "থ্রুপুট", "pronunciation": "থ্রুপুট" },
    { "word": "latency", "meaning": "লেটেন্সি", "pronunciation": "লেটেন্সি" },
    { "word": "encryption", "meaning": "এনক্রিপশন", "pronunciation": "এনক্রিপশন" },
    { "word": "decryption", "meaning": "ডিক্রিপশন", "pronunciation": "ডিক্রিপশন" },
    { "word": "token", "meaning": "টোকেন", "pronunciation": "টোকেন" },
    { "word": "session", "meaning": "সেশন", "pronunciation": "সেশন" },
    { "word": "cache", "meaning": "ক্যাশ", "pronunciation": "ক্যাশ" },
    { "word": "protocol", "meaning": "প্রোটোকল", "pronunciation": "প্রোটোকল" },
    { "word": "firmware", "meaning": "ফার্মওয়্যার", "pronunciation": "ফার্মওয়্যার" },
    { "word": "driver", "meaning": "ড্রাইভার", "pronunciation": "ড্রাইভার" },
    { "word": "authentication", "meaning": "অথেন্টিকেশন", "pronunciation": "অথেন্টিকেশন" },
    { "word": "authorization", "meaning": "অথরাইজেশন", "pronunciation": "অথরাইজেশন" },
    { "word": "configuration", "meaning": "কনফিগারেশন", "pronunciation": "কনফিগারেশন" },
    { "word": "deployment", "meaning": "ডিপ্লয়মেন্ট", "pronunciation": "ডিপ্লয়মেন্ট" },
    { "word": "virtualization", "meaning": "ভার্চুয়ালাইজেশন", "pronunciation": "ভার্চুয়ালাইজেশন" },
    { "word": "cloud computing", "meaning": "ক্লাউড কম্পিউটিং", "pronunciation": "ক্লাউড কম্পিউটিং" },
    { "word": "big data", "meaning": "বিগ ডেটা", "pronunciation": "বিগ ডেটা" },
    { "word": "machine learning", "meaning": "মেশিন লার্নিং", "pronunciation": "মেশিন লার্নিং" },
    { "word": "artificial intelligence", "meaning": "কৃত্রিম বুদ্ধিমত্তা", "pronunciation": "আর্টিফিশিয়াল ইনটেলিজেন্স" },
    { "word": "blockchain", "meaning": "ব্লকচেইন", "pronunciation": "ব্লকচেইন" },
    { "word": "quantum computing", "meaning": "কোয়ান্টাম কম্পিউটিং", "pronunciation": "কোয়ান্টাম কম্পিউটিং" },
    { "word": "office", "meaning": "অফিস", "pronunciation": "অফিস" },
    { "word": "meeting", "meaning": "মিটিং", "pronunciation": "মিটিং" },
    { "word": "deadline", "meaning": "ডেডলাইন", "pronunciation": "ডেডলাইন" },
    { "word": "project", "meaning": "প্রকল্প", "pronunciation": "প্রজেক্ট" },
    { "word": "report", "meaning": "রিপোর্ট", "pronunciation": "রিপোর্ট" },
    { "word": "presentation", "meaning": "প্রেজেন্টেশন", "pronunciation": "প্রেজেন্টেশন" },
    { "word": "schedule", "meaning": "সূচি", "pronunciation": "শিডিউল" },
    { "word": "agenda", "meaning": "এজেন্ডা", "pronunciation": "এজেন্ডা" },
    { "word": "document", "meaning": "ডকুমেন্ট", "pronunciation": "ডকুমেন্ট" },
    { "word": "file", "meaning": "ফাইল", "pronunciation": "ফাইল" },
    { "word": "email", "meaning": "ইমেল", "pronunciation": "ইমেল" },
    { "word": "memo", "meaning": "মেমো", "pronunciation": "মেমো" },
    { "word": "invoice", "meaning": "চালান", "pronunciation": "ইনভয়েস" },
    { "word": "budget", "meaning": "বাজেট", "pronunciation": "বাজেট" },
    { "word": "expense", "meaning": "ব্যয়", "pronunciation": "এক্সপেন্স" },
    { "word": "salary", "meaning": "বেতন", "pronunciation": "স্যালারি" },
    { "word": "promotion", "meaning": "প্রমোশন", "pronunciation": "প্রমোশন" },
    { "word": "meeting room", "meaning": "মিটিং রুম", "pronunciation": "মিটিং রুম" },
    { "word": "conference", "meaning": "সন্মেলন", "pronunciation": "কনফারেন্স" },
    { "word": "workspace", "meaning": "কর্মস্থল", "pronunciation": "ওয়ার্কস্পেস" },
    { "word": "team", "meaning": "দল", "pronunciation": "টিম" },
    { "word": "colleague", "meaning": "সহকর্মী", "pronunciation": "কলিগ" },
    { "word": "manager", "meaning": "ব্যবস্থাপক", "pronunciation": "ম্যানেজার" },
    { "word": "supervisor", "meaning": "পর্যবেক্ষক", "pronunciation": "সুপারভাইজার" },
    { "word": "assistant", "meaning": "সহায়ক", "pronunciation": "অ্যাসিস্ট্যান্ট" },
    { "word": "HR", "meaning": "এইচআর", "pronunciation": "এইচআর" },
    { "word": "recruitment", "meaning": "ভর্তির প্রক্রিয়া", "pronunciation": "রেক্রুটমেন্ট" },
    { "word": "training", "meaning": "প্রশিক্ষণ", "pronunciation": "ট্রেইনিং" },
    { "word": "performance", "meaning": "পারফরম্যান্স", "pronunciation": "পারফরম্যান্স" },
    { "word": "feedback", "meaning": "মতামত", "pronunciation": "ফিডব্যাক" },
    { "word": "task", "meaning": "কাজ", "pronunciation": "টাস্ক" },
    { "word": "deadline", "meaning": "ডেডলাইন", "pronunciation": "ডেডলাইন" },
    { "word": "goal", "meaning": "লক্ষ্য", "pronunciation": "গোল" },
    { "word": "objectives", "meaning": "উদ্দেশ্য", "pronunciation": "অবজেকটিভস" },
    { "word": "strategy", "meaning": "কৌশল", "pronunciation": "স্ট্র্যাটেজি" },
    { "word": "planning", "meaning": "পরিকল্পনা", "pronunciation": "প্ল্যানিং" },
    { "word": "organization", "meaning": "সংগঠন", "pronunciation": "অর্গানাইজেশন" },
    { "word": "management", "meaning": "ব্যবস্থাপনা", "pronunciation": "ম্যানেজমেন্ট" },
    { "word": "leadership", "meaning": "নেতৃত্ব", "pronunciation": "লিডারশিপ" },
    { "word": "strategy", "meaning": "কৌশল", "pronunciation": "স্ট্র্যাটেজি" },
    { "word": "workflow", "meaning": "ওয়ার্কফ্লো", "pronunciation": "ওয়ার্কফ্লো" },
    { "word": "update", "meaning": "আপডেট", "pronunciation": "আপডেট" },
    { "word": "meeting agenda", "meaning": "মিটিং এজেন্ডা", "pronunciation": "মিটিং এজেন্ডা" },
    { "word": "attendance", "meaning": "উপস্থিতি", "pronunciation": "অ্যাটেনডেন্স" },
    { "word": "briefing", "meaning": "ব্রিফিং", "pronunciation": "ব্রিফিং" },
    { "word": "reporting", "meaning": "রিপোর্টিং", "pronunciation": "রিপোর্টিং" },
    { "word": "record", "meaning": "রেকর্ড", "pronunciation": "রেকর্ড" },
    { "word": "archive", "meaning": "আর্কাইভ", "pronunciation": "আর্কাইভ" },
    { "word": "documentation", "meaning": "ডকুমেন্টেশন", "pronunciation": "ডকুমেন্টেশন" },
    { "word": "meeting minutes", "meaning": "মিটিং মিনিটস", "pronunciation": "মিটিং মিনিটস" },
    { "word": "calendar", "meaning": "পঞ্জিকা", "pronunciation": "ক্যালেন্ডার" },
    { "word": "schedule", "meaning": "তালিকা", "pronunciation": "শিডিউল" },
    { "word": "notification", "meaning": "বিজ্ঞপ্তি", "pronunciation": "নোটিফিকেশন" },
    { "word": "alert", "meaning": "সতর্কতা", "pronunciation": "এলার্ট" },
    { "word": "deadline", "meaning": "ডেডলাইন", "pronunciation": "ডেডলাইন" },
    { "word": "task list", "meaning": "টাস্ক তালিকা", "pronunciation": "টাস্ক লিস্ট" },
    { "word": "priority", "meaning": "অগ্রাধিকার", "pronunciation": "প্রায়রিটি" },
    { "word": "workflow", "meaning": "ওয়ার্কফ্লো", "pronunciation": "ওয়ার্কফ্লো" },
    { "word": "deadline", "meaning": "ডেডলাইন", "pronunciation": "ডেডলাইন" },
    { "word": "appointment", "meaning": "অ্যাপয়েন্টমেন্ট", "pronunciation": "অ্যাপয়েন্টমেন্ট" },
    { "word": "conference call", "meaning": "কনফারেন্স কল", "pronunciation": "কনফারেন্স কল" },
    { "word": "minutes", "meaning": "মিনিটস", "pronunciation": "মিনিটস" },
    { "word": "agenda", "meaning": "এজেন্ডা", "pronunciation": "এজেন্ডা" },
    { "word": "team building", "meaning": "টিম বিল্ডিং", "pronunciation": "টিম বিল্ডিং" },
    { "word": "brainstorming", "meaning": "ব্রেইনস্টর্মিং", "pronunciation": "ব্রেইনস্টর্মিং" },
    { "word": "outlook", "meaning": "আউটলুক", "pronunciation": "আউটলুক" },
    { "word": "minutes of meeting", "meaning": "মিটিংয়ের মিনিটস", "pronunciation": "মিটিংয়ের মিনিটস" },
    { "word": "teleconference", "meaning": "টেলিকনফারেন্স", "pronunciation": "টেলিকনফারেন্স" },
    { "word": "resource allocation", "meaning": "সম্পদ বরাদ্দ", "pronunciation": "রিসোর্স অ্যালোকেশন" },
    { "word": "deliverable", "meaning": "ডেলিভারেবল", "pronunciation": "ডেলিভারেবল" },
    { "word": "stakeholder", "meaning": "স্টেকহোল্ডার", "pronunciation": "স্টেকহোল্ডার" },
    { "word": "benchmark", "meaning": "বেঞ্চমার্ক", "pronunciation": "বেঞ্চমার্ক" },
    { "word": "strategy meeting", "meaning": "স্ট্র্যাটেজি মিটিং", "pronunciation": "স্ট্র্যাটেজি মিটিং" },
    { "word": "networking", "meaning": "নেটওয়ার্কিং", "pronunciation": "নেটওয়ার্কিং" },
    { "word": "collaboration", "meaning": "সহযোগিতা", "pronunciation": "কোলাবরেশন" },
    { "word": "feedback session", "meaning": "ফিডব্যাক সেশন", "pronunciation": "ফিডব্যাক সেশন" },
    { "word": "performance review", "meaning": "পারফরম্যান্স রিভিউ", "pronunciation": "পারফরম্যান্স রিভিউ" },
    { "word": "project plan", "meaning": "প্রকল্প পরিকল্পনা", "pronunciation": "প্রজেক্ট প্ল্যান" },
    { "word": "task management", "meaning": "টাস্ক ব্যবস্থাপনা", "pronunciation": "টাস্ক ম্যানেজমেন্ট" },
    { "word": "office supplies", "meaning": "অফিস সরবরাহ", "pronunciation": "অফিস সাপ্লাইস" },
    { "word": "administrative tasks", "meaning": "প্রশাসনিক কাজ", "pronunciation": "অ্যাডমিনিস্ট্রেটিভ টাস্কস" },
    { "word": "travel arrangements", "meaning": "ভ্রমণ ব্যবস্থা", "pronunciation": "ট্রাভেল অ্যারেঞ্জমেন্টস" },
    { "word": "workstation", "meaning": "ওয়ার্কস্টেশন", "pronunciation": "ওয়ার্কস্টেশন" },
    { "word": "confidentiality", "meaning": "গোপনীয়তা", "pronunciation": "কনফিডেনশিয়ালিটি" },
    { "word": "work-life balance", "meaning": "কর্মজীবন ও ব্যক্তিগত জীবনের ভারসাম্য", "pronunciation": "ওয়ার্ক-লাইফ ব্যালেন্স" },
    { "word": "meeting room", "meaning": "মিটিং রুম", "pronunciation": "মিটিং রুম" },
    { "word": "office chair", "meaning": "অফিস চেয়ার", "pronunciation": "অফিস চেয়ার" },
    { "word": "cubicle", "meaning": "কিউবিকল", "pronunciation": "কিউবিকল" },
    { "word": "desk", "meaning": "ডেস্ক", "pronunciation": "ডেস্ক" },
    { "word": "printer", "meaning": "প্রিন্টার", "pronunciation": "প্রিন্টার" },
    { "word": "scanner", "meaning": "স্ক্যানার", "pronunciation": "স্ক্যানার" },
    { "word": "fax", "meaning": "ফ্যাক্স", "pronunciation": "ফ্যাক্স" },
    { "word": "telephone", "meaning": "টেলিফোন", "pronunciation": "টেলিফোন" },
    { "word": "internet", "meaning": "ইন্টারনেট", "pronunciation": "ইন্টারনেট" },
    { "word": "software", "meaning": "সফটওয়্যার", "pronunciation": "সফটওয়্যার" },
    { "word": "hardware", "meaning": "হার্ডওয়্যার", "pronunciation": "হার্ডওয়্যার" },
    { "word": "application", "meaning": "অ্যাপ্লিকেশন", "pronunciation": "অ্যাপ্লিকেশন" },
    { "word": "database", "meaning": "ডেটাবেস", "pronunciation": "ডেটাবেস" },
    { "word": "spreadsheet", "meaning": "স্প্রেডশীট", "pronunciation": "স্প্রেডশীট" },
    { "word": "file folder", "meaning": "ফাইল ফোল্ডার", "pronunciation": "ফাইল ফোল্ডার" },
    { "word": "binder", "meaning": "বাইন্ডার", "pronunciation": "বাইন্ডার" },
    { "word": "envelope", "meaning": "খাম", "pronunciation": "এনভেলপ" },
    { "word": "post-it notes", "meaning": "পোস্ট-ইট নোটস", "pronunciation": "পোস্ট-ইট নোটস" },
    { "word": "calendar", "meaning": "পঞ্জিকা", "pronunciation": "ক্যালেন্ডার" },
    { "word": "notebook", "meaning": "নোটবুক", "pronunciation": "নোটবুক" },
    { "word": "pen", "meaning": "কলম", "pronunciation": "পেন" },
    { "word": "pencil", "meaning": "পেন্সিল", "pronunciation": "পেন্সিল" },
    { "word": "eraser", "meaning": "রাবার", "pronunciation": "এরাসার" },
    { "word": "highlighter", "meaning": "হাইলাইটার", "pronunciation": "হাইলাইটার" },
    { "word": "health", "meaning": "স্বাস্থ্য", "pronunciation": "হেলথ" },
    { "word": "doctor", "meaning": "ডাক্তার", "pronunciation": "ডাক্তার" },
    { "word": "nurse", "meaning": "নার্স", "pronunciation": "নার্স" },
    { "word": "hospital", "meaning": "হাসপাতাল", "pronunciation": "হাসপাতাল" },
    { "word": "clinic", "meaning": "ক্লিনিক", "pronunciation": "ক্লিনিক" },
    { "word": "medicine", "meaning": "ওষুধ", "pronunciation": "মেডিসিন" },
    { "word": "prescription", "meaning": "প্রেসক্রিপশন", "pronunciation": "প্রেসক্রিপশন" },
    { "word": "pharmacy", "meaning": "ফার্মেসি", "pronunciation": "ফার্মেসি" },
    { "word": "treatment", "meaning": "চিকিৎসা", "pronunciation": "ট্রিটমেন্ট" },
    { "word": "surgery", "meaning": "সার্জারি", "pronunciation": "সার্জারি" },
    { "word": "diagnosis", "meaning": "নির্ণয়", "pronunciation": "ডায়াগনোসিস" },
    { "word": "symptom", "meaning": "উপসর্গ", "pronunciation": "সিম্পটম" },
    { "word": "condition", "meaning": "অবস্থা", "pronunciation": "কন্ডিশন" },
    { "word": "check-up", "meaning": "চেক-আপ", "pronunciation": "চেক-আপ" },
    { "word": "vaccination", "meaning": "টিকাদান", "pronunciation": "ভ্যাকসিনেশন" },
    { "word": "allergy", "meaning": "অ্যালার্জি", "pronunciation": "অ্যালার্জি" },
    { "word": "infection", "meaning": "সংক্রমণ", "pronunciation": "ইনফেকশন" },
    { "word": "fever", "meaning": "জ্বর", "pronunciation": "ফিভার" },
    { "word": "cough", "meaning": "কাশি", "pronunciation": "কফ" },
    { "word": "cold", "meaning": "সর্দি", "pronunciation": "কোল্ড" },
    { "word": "flu", "meaning": "ফ্লু", "pronunciation": "ফ্লু" },
    { "word": "pain", "meaning": "ব্যথা", "pronunciation": "পেইন" },
    { "word": "headache", "meaning": "মাথাব্যথা", "pronunciation": "হেডেক" },
    { "word": "stomachache", "meaning": "পেটব্যথা", "pronunciation": "স্টোম্যাকেক" },
    { "word": "backache", "meaning": "পিঠব্যথা", "pronunciation": "ব্যাকএচ" },
    { "word": "treatment", "meaning": "চিকিৎসা", "pronunciation": "ট্রিটমেন্ট" },
    { "word": "surgery", "meaning": "সার্জারি", "pronunciation": "সার্জারি" },
    { "word": "check-up", "meaning": "চেক-আপ", "pronunciation": "চেক-আপ" },
    { "word": "therapy", "meaning": "থেরাপি", "pronunciation": "থেরাপি" },
    { "word": "rehabilitation", "meaning": "পুনর্বাসন", "pronunciation": "রিহ্যাবিলিটেশন" },
    { "word": "healthcare", "meaning": "স্বাস্থ্যসেবা", "pronunciation": "হেলথকেয়ার" },
    { "word": "insurance", "meaning": "বীমা", "pronunciation": "ইনসুরেন্স" },
    { "word": "emergency", "meaning": "জরুরি", "pronunciation": "ইমার্জেন্সি" },
    { "word": "ambulance", "meaning": "এম্বুলেন্স", "pronunciation": "এম্বুলেন্স" },
    { "word": "hospital bed", "meaning": "হাসপাতাল বিছানা", "pronunciation": "হাসপাতাল বেড" },
    { "word": "appointment", "meaning": "নিয়মিত পরিদর্শন", "pronunciation": "অ্যাপয়েন্টমেন্ট" },
    { "word": "examination", "meaning": "পরীক্ষা", "pronunciation": "এক্সামিনেশন" },
    { "word": "blood test", "meaning": "রক্ত পরীক্ষা", "pronunciation": "ব্লাড টেস্ট" },
    { "word": "urine test", "meaning": "মূত্র পরীক্ষা", "pronunciation": "ইউরিন টেস্ট" },
    { "word": "X-ray", "meaning": "এক্স-রে", "pronunciation": "এক্স-রে" },
    { "word": "MRI", "meaning": "এমআরআই", "pronunciation": "এমআরআই" },
    { "word": "CT scan", "meaning": "সিটি স্ক্যান", "pronunciation": "সিটি স্ক্যান" },
    { "word": "physiotherapy", "meaning": "ফিজিওথেরাপি", "pronunciation": "ফিজিওথেরাপি" },
    { "word": "occupational therapy", "meaning": "অকুপেশনাল থেরাপি", "pronunciation": "অকুপেশনাল থেরাপি" },
    { "word": "diet", "meaning": "ডায়েট", "pronunciation": "ডায়েট" },
    { "word": "nutrition", "meaning": "পুষ্টি", "pronunciation": "নিউট্রিশন" },
    { "word": "exercise", "meaning": "ব্যায়াম", "pronunciation": "এক্সারসাইজ" },
    { "word": "fitness", "meaning": "ফিটনেস", "pronunciation": "ফিটনেস" },
    { "word": "weight", "meaning": "ওজন", "pronunciation": "ওয়েট" },
    { "word": "height", "meaning": "উচ্চতা", "pronunciation": "হাইট" },
    { "word": "blood pressure", "meaning": "রক্তচাপ", "pronunciation": "ব্লাড প্রেসার" },
    { "word": "cholesterol", "meaning": "কোলেস্টেরল", "pronunciation": "কোলেস্টেরল" },
    { "word": "sugar level", "meaning": "সুগার লেভেল", "pronunciation": "সুগার লেভেল" },
    { "word": "heart rate", "meaning": "হৃদপিণ্ডের গতি", "pronunciation": "হার্ট রেট" },
    { "word": "vaccination", "meaning": "টিকাদান", "pronunciation": "ভ্যাকসিনেশন" },
    { "word": "allergy", "meaning": "অ্যালার্জি", "pronunciation": "অ্যালার্জি" },
    { "word": "infection", "meaning": "সংক্রমণ", "pronunciation": "ইনফেকশন" },
    { "word": "contagious", "meaning": "সংক্রামক", "pronunciation": "কন্টেজিয়াস" },
    { "word": "chronic", "meaning": "দীর্ঘস্থায়ী", "pronunciation": "ক্রনিক" },
    { "word": "acute", "meaning": "তীব্র", "pronunciation": "অ্যাকিউট" },
    { "word": "rehab", "meaning": "পুনর্বাসন", "pronunciation": "রিহ্যাব" },
    { "word": "wellness", "meaning": "স্বাস্থ্যবান", "pronunciation": "ওয়েলনেস" },
    { "word": "mental health", "meaning": "মেন্টাল হেলথ", "pronunciation": "মেন্টাল হেলথ" },
    { "word": "physical health", "meaning": "শারীরিক স্বাস্থ্য", "pronunciation": "ফিজিক্যাল হেলথ" },
    { "word": "happiness", "meaning": "খুশি", "pronunciation": "হ্যাপিনেস" },
    { "word": "joy", "meaning": "আনন্দ", "pronunciation": "জয়" },
    { "word": "sadness", "meaning": "দুঃখ", "pronunciation": "সাডনেস" },
    { "word": "anger", "meaning": "রাগ", "pronunciation": "অ্যাঙ্গার" },
    { "word": "fear", "meaning": "ভয়", "pronunciation": "ফিয়ার" },
    { "word": "surprise", "meaning": "আশ্চর্য", "pronunciation": "সারপ্রাইজ" },
    { "word": "disgust", "meaning": "ঘৃণা", "pronunciation": "ডিসগাস্ট" },
    { "word": "confusion", "meaning": "বিভ্রান্তি", "pronunciation": "কনফিউশন" },
    { "word": "pride", "meaning": "গর্ব", "pronunciation": "প্রাইড" },
    { "word": "shame", "meaning": "লজ্জা", "pronunciation": "শেইম" },
    { "word": "embarrassment", "meaning": "বিব্রততা", "pronunciation": "এম্বারাসমেন্ট" },
    { "word": "relief", "meaning": "মুক্তি", "pronunciation": "রিলিফ" },
    { "word": "frustration", "meaning": "বিক্ষোভ", "pronunciation": "ফ্রাস্ট্রেশন" },
    { "word": "hope", "meaning": "আশা", "pronunciation": "হোপ" },
    { "word": "love", "meaning": "ভালোবাসা", "pronunciation": "লাভ" },
    { "word": "affection", "meaning": "স্নেহ", "pronunciation": "অ্যাফেকশন" },
    { "word": "boredom", "meaning": "বোরিং", "pronunciation": "বোরডম" },
    { "word": "excitement", "meaning": "উচ্ছ্বাস", "pronunciation": "এক্সাইটমেন্ট" },
    { "word": "loneliness", "meaning": "একাকীত্ব", "pronunciation": "লোনলিনেস" },
    { "word": "contentment", "meaning": "সন্তুষ্টি", "pronunciation": "কনটেন্টমেন্ট" },
    { "word": "guilt", "meaning": "অপরাধবোধ", "pronunciation": "গিল্ট" },
    { "word": "jealousy", "meaning": "হিংসা", "pronunciation": "জেলাসি" },
    { "word": "resentment", "meaning": "ক্ষোভ", "pronunciation": "রেসেন্টমেন্ট" },
    { "word": "grief", "meaning": "বেদনা", "pronunciation": "গ্রিফ" },
    { "word": "panic", "meaning": "পানিক", "pronunciation": "প্যানিক" },
    { "word": "euphoria", "meaning": "উত্তেজনা", "pronunciation": "ইউফোরিয়া" },
    { "word": "melancholy", "meaning": "মলিনতা", "pronunciation": "মেলানকোলি" },
    { "word": "tranquility", "meaning": "শান্তি", "pronunciation": "ট্রাঙ্কুইলিটি" },
    { "word": "anger management", "meaning": "রাগ ব্যবস্থাপনা", "pronunciation": "অ্যাঙ্গার ম্যানেজমেন্ট" },
    { "word": "anxiety", "meaning": "উদ্বেগ", "pronunciation": "অ্যাংজাইটি" },
    { "word": "serenity", "meaning": "শান্তি", "pronunciation": "সিরেনিটি" },
    { "word": "ecstasy", "meaning": "আনন্দ", "pronunciation": "একস্টেসি" },
    { "word": "indifference", "meaning": "উদাসীনতা", "pronunciation": "ইন্ডিফারেন্স" },
    { "word": "sympathy", "meaning": "সহানুভূতি", "pronunciation": "সিম্প্যাথি" },
    { "word": "empathy", "meaning": "সহানুভূতি", "pronunciation": "এমপ্যাথি" },
    { "word": "sorrow", "meaning": "দুঃখ", "pronunciation": "সারো" },
    { "word": "pleasure", "meaning": "আনন্দ", "pronunciation": "প্লেজার" },
    { "word": "disappointment", "meaning": "নিরাশা", "pronunciation": "ডিসঅ্যাপয়েন্টমেন্ট" },
    { "word": "frustration", "meaning": "অব্যাহত অবস্থা", "pronunciation": "ফ্রাস্ট্রেশন" },
    { "word": "rage", "meaning": "খুব রাগ", "pronunciation": "রেজ" },
    { "word": "dread", "meaning": "ভয়", "pronunciation": "ড্রেড" },
    { "word": "elation", "meaning": "উচ্ছ্বাস", "pronunciation": "এলেশন" },
    { "word": "displeasure", "meaning": "অসন্তুষ্টি", "pronunciation": "ডিসপ্লেজার" },
    { "word": "content", "meaning": "সন্তুষ্ট", "pronunciation": "কনটেন্ট" },
    { "word": "resent", "meaning": "অপ্রসন্নতা", "pronunciation": "রেসেন্ট" },
    { "word": "satisfaction", "meaning": "সন্তোষ", "pronunciation": "স্যাটিসফ্যাকশন" },
    { "word": "yearning", "meaning": "আকাঙ্ক্ষা", "pronunciation": "ইয়ার্নিং" },
    { "word": "compassion", "meaning": "দয়া", "pronunciation": "কম্প্যাশন" },
    { "word": "infatuation", "meaning": "মোহ", "pronunciation": "ইনফ্যাচুয়েশন" },
    { "word": "embarrassed", "meaning": "বিব্রত", "pronunciation": "এম্বারাসড" },
    { "word": "relieved", "meaning": "মুক্তি পেয়েছে", "pronunciation": "রিলিভড" },
    { "word": "horrified", "meaning": "ভয়ঙ্কর", "pronunciation": "হরিফাইড" },
    { "word": "overwhelmed", "meaning": "অবশ", "pronunciation": "ওভারওয়েলমড" },
    { "word": "unsettled", "meaning": "অস্থিতিশীল", "pronunciation": "আনসেটলড" },
    { "word": "tired", "meaning": "ক্লান্ত", "pronunciation": "টাইয়ারড" },
    { "word": "hopeful", "meaning": "আশাবাদী", "pronunciation": "হোপফুল" },
    { "word": "miserable", "meaning": "দুঃখিত", "pronunciation": "মিজারেবল" },
    { "word": "excited", "meaning": "উচ্ছ্বসিত", "pronunciation": "এক্সাইটেড" },
    

    
    
    
];




function StartTest() {
    document.getElementById('quiz-section').style.display = 'block';
    document.getElementById('practice-section').style.display = 'none';
    generateQuestion();
}

function generateQuestion() {
    let word = words[Math.floor(Math.random() * words.length)];
    document.getElementById('question').innerText = `What is the meaning of "${word.word}"?`;
    let correctOption = Math.floor(Math.random() * 4);
    let options = document.getElementsByClassName('option');
    
    for (let i = 0; i < 4; i++) {
        if (i === correctOption) {
            options[i].innerText = `${word.meaning} (${word.pronunciation})`;
            options[i].onclick = () => showFeedback(true);
        } else {
            let incorrectWord;
            do {
                incorrectWord = words[Math.floor(Math.random() * words.length)];
            } while (incorrectWord.meaning === word.meaning);
            options[i].innerText = `${incorrectWord.meaning} (${incorrectWord.pronunciation})`;
            options[i].onclick = () => showFeedback(false);
        }
    }
}

function showFeedback(isCorrect) {
    let feedback = document.getElementById('feedback');
    if (isCorrect) {
        feedback.innerText = "Correct!";
        feedback.style.color = "green";
    } else {
        feedback.innerText = "Wrong! Try again.";
        feedback.style.color = "red";
    }
    setTimeout(generateQuestion, 2000);
}

function startPractice() {
    document.getElementById('quiz-section').style.display = 'none';
    document.getElementById('practice-section').style.display = 'block';
    nextWord();
}

function nextWord() {
    let word = words[Math.floor(Math.random() * words.length)];
    document.getElementById('practice-word').innerText = word.word;
    document.getElementById('practice-meaning').innerText = `Meaning: ${word.meaning}`;
    document.getElementById('practice-pronunciation').innerText = `Pronunciation: ${word.pronunciation}`;
}

function viewProgress() {
    alert("Progress tracking is not implemented yet.");
}





function generateQuestion() {
    let word = words[Math.floor(Math.random() * words.length)];
    let correctAnswer = word.meaning;  // Store the correct answer

    document.getElementById('question').innerText = `What is the Bengali meaning of "${word.word} (${word.pronunciation})"?`;
    
    let correctOption = Math.floor(Math.random() * 4);
    let options = document.getElementsByClassName('option');
    
    for (let i = 0; i < 4; i++) {
        if (i === correctOption) {
            options[i].innerText = correctAnswer;
            options[i].onclick = () => showFeedback(true, correctAnswer);
        } else {
            let incorrectWord;
            do {
                incorrectWord = words[Math.floor(Math.random() * words.length)];
            } while (incorrectWord.meaning === word.meaning);
            options[i].innerText = incorrectWord.meaning;
            options[i].onclick = () => showFeedback(false, correctAnswer);
        }
    }
}



let totalQuestions = 0;
let correctAnswers = 0;
function showFeedback(isCorrect) {
    totalQuestions++; // Increment total questions answered
    let feedback = document.getElementById('feedback');
    if (isCorrect) {
        correctAnswers++; // Increment correct answers if correct
        feedback.innerText = "Correct!";
        feedback.style.color = "green";
    } else {
        feedback.innerText = "Wrong! Try again.";
        feedback.style.color = "red";
    }
    setTimeout(generateQuestion, 2000);
}
function viewProgress() {
    let progressMessage = `You have answered ${totalQuestions} questions and got ${correctAnswers} correct.`;
    alert(progressMessage);
}


function showFeedback(isCorrect, correctAnswer) {
    totalQuestions++; // Increment total questions answered
    let feedback = document.getElementById('feedback');
    
    if (isCorrect) {
        correctAnswers++; // Increment correct answers if correct
        feedback.innerText = "Correct!";
        feedback.style.color = "green";
    } else {
        feedback.innerText = `Wrong! The correct answer is: ${correctAnswer}`;
        feedback.style.color = "red";
    }
    
    setTimeout(generateQuestion, 1000);
}




let totalLikes = 0;

document.getElementById('like-button').addEventListener('click', function() {
    totalLikes++;
    document.getElementById('total-likes').innerText = totalLikes;
});

let currentWordIndex = 0; // To track the current position in the shuffled array
let shuffledIndexes = []; // Array to store the order of shuffled word indexes
let seenWords = []; // Array to track the seen words

// Shuffle Array Helper Function
function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

// Function to initialize shuffled word order
function initShuffle() {
    shuffledIndexes = Array.from({ length: words.length }, (_, i) => i);
    shuffleArray(shuffledIndexes); // Shuffle the index order
}

// Function to display the current word
function displayWord(index) {
    const word = words[index];
    document.getElementById('practice-word').innerText = word.word;
    document.getElementById('practice-meaning').innerText = `Meaning: ${word.meaning}`;
    document.getElementById('practice-pronunciation').innerText = `Pronunciation: ${word.pronunciation}`;
}

// Function to get the next word
function nextWord() {
    if (currentWordIndex < shuffledIndexes.length - 1) {
        currentWordIndex++;
        displayWord(shuffledIndexes[currentWordIndex]);
        seenWords.push(shuffledIndexes[currentWordIndex]); // Keep track of the seen words
    } else {
        alert("You have practiced all the words!");
    }
}

// Function to get the previous word
function previousWord() {
    if (currentWordIndex > 0) {
        currentWordIndex--;
        displayWord(shuffledIndexes[currentWordIndex]);
    } else {
        alert("You're already at the first word.");
    }
}

// Initialize by displaying the first shuffled word
document.addEventListener('DOMContentLoaded', function() {
    initShuffle(); // Initialize shuffled order
    displayWord(shuffledIndexes[currentWordIndex]); // Display the first word
});

// Button listeners for next and previous
document.getElementById('next-button').addEventListener('click', nextWord);
document.getElementById('previous-button').addEventListener('click', previousWord);


